In [1]:
import tensorflow as tf

C:\Users\Cheng\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
X = tf.Variable([[0.4,0.2,0.4]])
W = tf.Variable([[-0.5,-0.2],
                 [-0.3,0.4],
                 [-0.5,0.2]])

b = tf.Variable([[0.1,0.2]])
XWb = tf.matmul(X,W) + b
y=tf.nn.relu(tf.matmul(X,W)+b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:');print(sess.run(XWb))
    print('y:');print(sess.run(y))

XWb:
[[-0.36000004  0.28      ]]
y:
[[0.   0.28]]


In [3]:
X = tf.Variable([[0.4,0.2,0.4]])
W = tf.Variable([[-0.5,-0.2],
                 [-0.3,0.4],
                 [-0.5,0.2]])

b = tf.Variable([[0.1,0.2]])
XWb = tf.matmul(X,W) + b
y=tf.nn.sigmoid(tf.matmul(X,W)+b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:');print(sess.run(XWb))
    print('y:');print(sess.run(y))

XWb:
[[-0.36000004  0.28      ]]
y:
[[0.41095954 0.5695462 ]]


In [4]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([1,2]))
X = tf.Variable([[0.4,0.2,0.4]])
y = tf.nn.relu(tf.matmul(X,W)+b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('b:');print(sess.run(b))
    print('W:');print(sess.run(W))
    print('y:');print(sess.run(y))
                

b:
[[-1.4970522  0.2610488]]
W:
[[ 1.2712184   0.46073842]
 [ 0.3063255  -0.82256854]
 [ 0.75509715  0.7280417 ]]
y:
[[0.        0.5720471]]


In [5]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([1,2]))
X = tf.Variable([[0.4,0.2,0.4]])
y = tf.nn.relu(tf.matmul(X,W)+b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    (_b,_W,_y) = sess.run((b,W,y))
    print('b:')
    print(_b)
    print('W:')
    print(_W)
    print('y:')
    print(_y)

b:
[[-0.19359148 -1.5589753 ]]
W:
[[ 1.3213915   0.02941797]
 [-0.51481295  0.9441283 ]
 [-0.39751586  0.87693924]]
y:
[[0.07299617 0.        ]]


In [6]:
import numpy as np
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([1,2]))
X = tf.placeholder("float",[None,3])
y = tf.nn.relu(tf.matmul(X,W)+b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4,0.2,0.4]])
    (_b,_W,_y) = sess.run((b,W,y),feed_dict={X:X_array})
    print('b:')
    print(_b)
    print('W:')
    print(_W)
    print('y:')
    print(_y)

b:
[[0.6935373 0.5904182]]
W:
[[ 0.05705361  0.3213399 ]
 [ 0.05285475  0.49119422]
 [-1.4182988  -0.17641759]]
y:
[[0.15961015 0.746626  ]]


In [7]:
import numpy as np
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([1,2]))
X = tf.placeholder("float",[None,3])
y = tf.nn.relu(tf.matmul(X,W)+b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4,0.2,0.4],
                       [0.3,0.4,0.5],
                       [0.3,-0.4,0.5]])
    (_b,_W,_y) = sess.run((b,W,y),feed_dict={X:X_array})
    print('b:')
    print(_b)
    print('W:')
    print(_W)
    print('y:')
    print(_y)

b:
[[ 1.6648107  -0.42802197]]
W:
[[ 0.38185203  0.00354607]
 [ 0.98866487 -0.7910595 ]
 [-1.5668468  -0.82836187]]
y:
[[1.3885458  0.        ]
 [1.3914088  0.        ]
 [0.60047686 0.        ]]


In [8]:
def layer(output_dim,input_dim,inputs,activation=None):
    W = tf.Variable(tf.random_normal([input_dim,output_dim]))
    b = tf.Variable(tf.random_normal([1,output_dim]))
    XWb = tf.matmul(inputs, W) + b
    if activation is None:
        outputs = XWb
    else:
        outputs = activation(XWb)
    return outputs

In [9]:
X = tf.placeholder("float",[None,4])
h = layer(output_dim=3,input_dim=4,inputs=X,activation=tf.nn.relu)
y = layer(output_dim=2, input_dim=3,inputs=h,activation=tf.nn.relu)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4,0.2,0.4,0.5]])
    (layer_X,layer_h,layer_y)=sess.run((X,h,y),feed_dict={X:X_array})
    print('input Layer X:');print(layer_X)
    print('hidden Layer h:');print(layer_h)
    print('output Layer y:');print(layer_y)

input Layer X:
[[0.4 0.2 0.4 0.5]]
hidden Layer h:
[[0.        2.2297761 0.       ]]
output Layer y:
[[0. 0.]]


In [10]:
def layer_debug(output_dim,input_dim,inputs,activation=None):
    W = tf.Variable(tf.random_normal([input_dim,output_dim]))
    b = tf.Variable(tf.random_normal([1,output_dim]))
    XWb = tf.matmul(inputs, W) + b
    if activation is None:
        outputs = XWb
    else:
        outputs = activation(XWb)
    return outputs,W,b

In [11]:
X = tf.placeholder("float",[None,4])
h,W1,b1 = layer_debug(output_dim=3,input_dim=4,inputs=X,activation=tf.nn.relu)
y,W2,b2 = layer_debug(output_dim=2, input_dim=3,inputs=h,activation=tf.nn.relu)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4,0.2,0.4,0.5]])
    (layer_X,layer_h,layer_y,W1,b1,W2,b2)=sess.run((X,h,y,W1,b1,W2,b2),feed_dict={X:X_array})
    print('input Layer X:');print(layer_X)
    print('W1:');print(W1)
    print('b1');print(b1)
    print('hidden Layer h:');print(layer_h)
    print('W2:');print(W2)
    print('b2');print(b2)
    print('output Layer y:');print(layer_y)

input Layer X:
[[0.4 0.2 0.4 0.5]]
W1:
[[ 0.48692992 -1.404191    0.13867468]
 [ 1.5082169   0.70173436 -1.0665488 ]
 [ 0.0542456   0.69790035  0.33494666]
 [-0.06346969 -2.0806634  -1.5468943 ]]
b1
[[0.8932587  0.73713505 0.03573233]]
hidden Layer h:
[[1.3796375 0.        0.       ]]
W2:
[[ 0.9120577  1.5155661]
 [-2.0088723 -1.0106348]
 [ 0.7053975  1.4190295]]
b2
[[ 1.7638803 -0.9448273]]
output Layer y:
[[3.0221891 1.1461046]]
