In [1]:
import tensorflow as tf
ts_c = tf.constant(2,name='ts_c')
ts_x = tf.Variable(ts_c+5,name='ts_x')

In [2]:
ts_c

<tf.Tensor 'ts_c:0' shape=() dtype=int32>

In [3]:
ts_x

In [9]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('ts_c=',ts_c.eval(session=sess))
    print('ts_x=',ts_x.eval(session=sess))

('ts_c=', 2)
('ts_x=', 7)


In [17]:
width = tf.placeholder("int32",name='width')
height = tf.placeholder("int32",name='height')
area = tf.multiply(width,height,name='area')

In [18]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area=',sess.run(area,feed_dict={width:6, height: 8}))

('area=', 48)


In [19]:
tf.summary.merge_all()
train_writer = tf.summary.FileWriter('log/area',sess.graph)

In [21]:
ts_X = tf.Variable([0.4,0.2,0.4])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_X)
    print X

[ 0.40000001  0.2         0.40000001]


In [22]:
print(X.shape)

(3,)


In [23]:
ts_X = tf.Variable([[0.4,0.2,0.4]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_X)
    print X

[[ 0.40000001  0.2         0.40000001]]


In [24]:
print('shape:',X.shape)

('shape:', (1, 3))


In [27]:
W = tf.Variable([[0.4,0.2],[1.0,2.0],[3.2,2.2]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    W_array = sess.run(W)
    print W_array

[[ 0.40000001  0.2       ]
 [ 1.          2.        ]
 [ 3.20000005  2.20000005]]


In [28]:
print(W_array.shape)

(3, 2)


In [31]:
X = tf.Variable([[1.,1.,1.]])

b = tf.Variable([[0.1,0.2]])

W = tf.Variable([[-0.5,-0.2],
                 [-0.3,0.4],
                 [-0.5,0.2]])

XWb = tf.matmul(X,W)+b



with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(XWb))

[[-1.19999993  0.60000002]]
