### Layers : Fundamental blocks of Neural Network

In [1]:
import torch
from torch.nn import Linear, ReLU
import torch.nn as nn
import numpy as np
from torch.autograd import Variable



In [2]:
myLayer = Linear(in_features=10,out_features=5,bias=True)
inp = Variable(torch.randn(1,10))
myLayer = Linear(in_features=10,out_features=5,bias=True) 
myLayer(inp)

tensor([[-1.0979,  1.5678,  0.4527, -0.3320, -0.6549]],
       grad_fn=<AddmmBackward>)

In [3]:
myLayer.weight

Parameter containing:
tensor([[-0.1872,  0.1448,  0.1691,  0.2177, -0.0253,  0.2614,  0.0111,  0.2100,
          0.2217, -0.2190],
        [ 0.0580, -0.2760,  0.2656,  0.2100,  0.1020,  0.1289,  0.0621, -0.1890,
          0.2701,  0.1167],
        [-0.0103,  0.0402,  0.1792, -0.2609,  0.1849,  0.2976, -0.0041,  0.0521,
         -0.0063,  0.1114],
        [ 0.2776, -0.1518, -0.2970,  0.0668,  0.2596, -0.1592,  0.0024,  0.2800,
         -0.2668,  0.1007],
        [ 0.1715, -0.0325, -0.1743,  0.2086,  0.1482,  0.0251,  0.1517, -0.1768,
         -0.2144, -0.1767]], requires_grad=True)

In [4]:
myLayer.bias

Parameter containing:
tensor([ 0.0173,  0.1678,  0.0894, -0.1147, -0.2486], requires_grad=True)

### Stacking Linear layers

In [5]:
myLayer1 = Linear(10,5)
myLayer2 = Linear(5,2)
myLayer2(myLayer1(inp))

tensor([[0.3846, 0.0842]], grad_fn=<AddmmBackward>)

### PyTorch Non-linear Activations

In [6]:
sample_data = Variable(torch.Tensor([[1,2,-1,-1]])) 
myRelu = ReLU()
myRelu(sample_data)


tensor([[1., 2., 0., 0.]])

In [7]:
import torch.nn as nn
import torch.nn.functional as F
sample_data = Variable(torch.Tensor([[1,2,-1,-1]])) 
f = F.relu(sample_data) # Much simpler.
f

tensor([[1., 2., 0., 0.]])

### Neural Network 

In [8]:
class MyFirstNetwork(nn.Module):
    def __init__(self,input_size,hidden_size,output_size):
        super(MyFirstNetwork,self).__init__() 
        self.layer1 = nn.Linear(input_size,hidden_size) 
        self.layer2 = nn.Linear(hidden_size,output_size)
    def __forward__(self,input): 
        out = self.layer1(input) 
        out = nn.ReLU(out)
        out = self.layer2(out) 
        return out

### Loss

In [9]:
loss = nn.MSELoss()
input = Variable(torch.randn(3, 5), requires_grad=True) 
target = Variable(torch.randn(3, 5))
output = loss(input, target)
output.backward()

分類問題常用的loss function: 交叉熵(cross-entropy)

In [10]:
def cross_entropy(true_label, prediction):
    if true_label == 1:
        return -log(prediction)
    else:
        return -log(1 - prediction)

In [11]:
loss = nn.CrossEntropyLoss()
input = Variable(torch.randn(3, 5), requires_grad=True) 
target = Variable(torch.LongTensor(3).random_(5)) 
output = loss(input, target)
output.backward()

### Optimizer

In [14]:
# for demo
import torch.optim as optim
model = nn.Linear(1,1)
optimizer = optim.SGD(model.parameters(), lr = 0.01,momentum=0.9)
for input, target in dataset:
    optimizer.zero_grad()
    output = model(input)
    loss = loss_fn(output, target)
    loss.backward()
    optimizer.step()

NameError: name 'dataset' is not defined